In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder 

In [3]:
data = pd.read_csv('lab02_dataset_1.csv')
data.columns

Index(['X', 'Y', 'Z', 'Class'], dtype='object')

In [4]:
data.head()

X         Y         Z     Class
0 -2.153269 -1.910092 -2.089200  Negative
1  3.354634 -1.803199 -2.849789  Negative
2 -2.773528  4.644997  2.412375  Positive
3  2.890608 -1.188494 -1.723388  Negative
4 -3.416683  4.789795  3.157649  Positive

In [5]:
classEncoder = OrdinalEncoder(categories=[list(data['Class'].unique())])
data['Class'] = classEncoder.fit_transform(data[['Class']]) 

In [6]:
data.head()

X         Y         Z  Class
0 -2.153269 -1.910092 -2.089200    0.0
1  3.354634 -1.803199 -2.849789    0.0
2 -2.773528  4.644997  2.412375    1.0
3  2.890608 -1.188494 -1.723388    0.0
4 -3.416683  4.789795  3.157649    1.0

In [9]:
def my_perceptron(data, labels, learning_rate=0.1, threshold=0.99, max_iterations=1000):
    n_samples, n_features = data.shape
    if n_samples != len(labels):
        raise ValueError("Input data and labels must have the same number of samples.")

    # Initialize weights with zeros and add a bias term for flexibility
    weights = np.zeros(n_features + 1)
    print(weights)
    # Training loop
    for epoch in range(max_iterations):
        correctly_classified = 0
        for i, (x, y) in enumerate(zip(data, labels)):
            # Add the bias term (assumed to be 1) to the input vector
            x_with_bias = np.append(x, 1)

            # Calculate the weighted sum and apply the activation function
            prediction = np.dot(weights, x_with_bias) >= 0

            # Update weights only for misclassified points
            if prediction != y:
                weights -= learning_rate * y * x_with_bias
            else:
                correctly_classified += 1

        # Calculate misclassification rate
        misclassified_rate = 1 - (correctly_classified / n_samples)

        # Early stopping if threshold is met
        if misclassified_rate < threshold:
            return weights

    # Return None if threshold not reached within max_iterations
    print("Warning: Perceptron algorithm did not converge within", max_iterations, "iterations.")
    return None

# Example usage
# data = np.array([[1, 2, 1], [3, 4, 4], [5, 6, 6], [7, 8, 8]])
# labels = np.array([1, -1, 1, -1])

data = np.array([[1, 2], [2, 3], [2, 1], [3, 0]])
labels = np.array([1, 1, 0, 0])

weights = my_perceptron(data, labels)

if weights is not None:
    print("Weights for linear separator:", weights)
else:
    print("Linear separator not found within convergence limit.")

[0. 0. 0.]
Weights for linear separator: [0. 0. 0.]


In [68]:
import numpy as np

def my_perceptron(X, y):
    # Append a column of 1s to X for bias
    X = np.hstack((np.ones((X.shape[0], 1)), X))
    
    # Initialize weights randomly
    np.random.seed(0)
    weights = np.random.rand(X.shape[1])
    
    # Perceptron learning rate
    learning_rate = 0.1
    
    # Maximum number of iterations
    max_iterations = 1000
    
    # Threshold for misclassification rate
    threshold = 0.01  # 1%
    
    # Perceptron algorithm
    iteration = 0
    while iteration < max_iterations:
        misclassified = 0
        for i in range(X.shape[0]):
            if np.dot(X[i], weights) >= 0:
                predicted_class = 1
            else:
                predicted_class = -1
            if predicted_class != y[i]:
                misclassified += 1
                weights += learning_rate * y[i] * X[i]
        misclassification_rate = misclassified / X.shape[0]
        if misclassification_rate < threshold:
            break
        iteration += 1
    
    return weights

# Example usage
# data = np.array([[1, 2, 1], [3, 4, 4], [5, 6, 6], [7, 8, 8]])
# labels = np.array([1, -1, 1, -1])

# data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
# labels = np.array([-1, -1, 1, 1, 1])
data = np.array([[1, 2], [2, 3], [2, 1], [3, 0]])
labels = np.array([1, 1, 0, 0])

weights = my_perceptron(data, labels)
print(weights)

[0.5488135  0.71518937 0.60276338]


In [ ]:
#  pip install plotly

In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder 

data = pd.read_csv('lab02_dataset_1.csv')
X = data.iloc[:, :-1].values
y = np.where(data.iloc[:, -1] == 'Positive', 1, 0)

In [66]:
def my_perceptron(X, y):

    learning_rate = 0.1 
    threshold = 0.99

    weights = np.zeros(len(X[0]))

    print(weights)

    print(range((len(X))))
    j=0
    i=0
    while i < len (X):
        print("=> ", weights, " and " ,X[i], " * ", np.dot(weights, X[i]))
        # print("INDEX : ", i)
        if np.dot(weights, X[i]) >= 0 and y[i] == 1:
            i+=1
        elif np.dot(weights, X[i]) < 0 and y[i] == 0:
            i+=1
        else:
            if y[i] == 1 : # "+"
                weights = np.add(weights, X[i])
                print("\nWeight after Adding : " , weights)
                i = 0
            else :  # "-"
                weights = np.subtract(weights, X[i])
                print("\nWeight after substract : " , weights)
                i = 0

    return weights


# X = np.array([[1, 2, 1] ,[1, -2, 1] ,[3, 1, 2], [2, 3, 2] ,[-1, 2, -2] ,[-1, -2, 4] ,[1, -3, -3] ,[-2, 4, -2] ,[4, 1, 3] ,[-1, 2, -4]])
# y = np.array([1, 0, 0, 1, 1, 0, 0, 1, 0, 1])
# weights = my_perceptron(X, y)
# print(weights)

# X = np.array([[1, 2], [2, 3], [2, 1], [3, 0]])
# y = np.array([1, 1, 0, 0])
# weights = my_perceptron(X, y)
# print(weights)

data = pd.read_csv('lab02_dataset_1.csv')
X = data.iloc[:, :-1].values
y = np.where(data.iloc[:, -1] == 'Positive', 1, 0)
weights = my_perceptron(X, y)
print(weights)
    

[0. 0. 0.]
range(0, 200)
=>  [0. 0. 0.]  and  [-2.15326928 -1.9100922  -2.08920045]  *  0.0

Weight after substract :  [2.15326928 1.9100922  2.08920045]
=>  [2.15326928 1.9100922  2.08920045]  and  [-2.15326928 -1.9100922  -2.08920045]  *  -12.6497793154754
=>  [2.15326928 1.9100922  2.08920045]  and  [ 3.35463418 -1.80319913 -2.84978878]  *  -2.1746258749319978
=>  [2.15326928 1.9100922  2.08920045]  and  [-2.77352781  4.64499734  2.41237452]  *  7.940154885797944
=>  [2.15326928 1.9100922  2.08920045]  and  [ 2.89060771 -1.18849411 -1.72338848]  *  0.3536194632779534

Weight after substract :  [-0.73733843  3.09858631  3.81258893]
=>  [-0.73733843  3.09858631  3.81258893]  and  [-2.15326928 -1.9100922  -2.08920045]  *  -12.296159852197444
=>  [-0.73733843  3.09858631  3.81258893]  and  [ 3.35463418 -1.80319913 -2.84978878]  *  -18.92594197436662
=>  [-0.73733843  3.09858631  3.81258893]  and  [-2.77352781  4.64499734  2.41237452]  *  25.635346170250862
=>  [-0.73733843  3.09858631  