In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import math

In [24]:
data = pd.read_csv('lab03_dataset_2.csv')
data.head()

CASE_ID  FRAUD  TOTAL_SPEND  DOCTOR_VISITS  NUM_CLAIMS  MEMBER_DURATION  \
0        1      1         1100             11           0               94   
1        2      1         1300              7           2              122   
2        3      1         1500              4           0              149   
3        4      1         1500              9           0              180   
4        5      0         1700              3           0               93   

   OPTOM_PRESC  NUM_MEMBERS  
0            1            2  
1            0            1  
2            1            3  
3            1            1  
4            0            1

#### 1) The input features used during training should be subjected to feature scaling, specifically the min-max scaling. (2 marks)

In [25]:
minMaxScaler = MinMaxScaler()
scaledData = minMaxScaler.fit_transform(data.iloc[:, 2:])
data.iloc[:, 2:]

TOTAL_SPEND  DOCTOR_VISITS  NUM_CLAIMS  MEMBER_DURATION  OPTOM_PRESC  \
0            1100             11           0               94            1   
1            1300              7           2              122            0   
2            1500              4           0              149            1   
3            1500              9           0              180            1   
4            1700              3           0               93            0   
...           ...            ...         ...              ...          ...   
5955        88900             16           0              222            0   
5956        89000             16           0              209            0   
5957        89200             15           0              212            0   
5958        89800             14           0              214            0   
5959        89900             15           0              220            0   

      NUM_MEMBERS  
0               2  
1               1  
2               3  
3               1  
4               1  
...           ...  
5955            2  
5956            4  
5957            2  
5958            2  
5959            1  

[5960 rows x 6 columns]

In [26]:
scaledData

array([[0.        , 0.26829268, 0.        , 0.14242424, 0.05882353,
        0.14285714],
       [0.00225225, 0.17073171, 0.13333333, 0.18484848, 0.        ,
        0.        ],
       [0.0045045 , 0.09756098, 0.        , 0.22575758, 0.05882353,
        0.28571429],
       ...,
       [0.99211712, 0.36585366, 0.        , 0.32121212, 0.        ,
        0.14285714],
       [0.99887387, 0.34146341, 0.        , 0.32424242, 0.        ,
        0.14285714],
       [1.        , 0.36585366, 0.        , 0.33333333, 0.        ,
        0.        ]])

In [27]:
data.columns[2:]

Index(['TOTAL_SPEND', 'DOCTOR_VISITS', 'NUM_CLAIMS', 'MEMBER_DURATION',
       'OPTOM_PRESC', 'NUM_MEMBERS'],
      dtype='object')

In [28]:
scaledInfo = pd.DataFrame(scaledData, columns=data.columns[2:])
scaledInfo.head()

TOTAL_SPEND  DOCTOR_VISITS  NUM_CLAIMS  MEMBER_DURATION  OPTOM_PRESC  \
0     0.000000       0.268293    0.000000         0.142424     0.058824   
1     0.002252       0.170732    0.133333         0.184848     0.000000   
2     0.004505       0.097561    0.000000         0.225758     0.058824   
3     0.004505       0.219512    0.000000         0.272727     0.058824   
4     0.006757       0.073171    0.000000         0.140909     0.000000   

   NUM_MEMBERS  
0     0.142857  
1     0.000000  
2     0.285714  
3     0.000000  
4     0.000000

In [29]:
X = scaledInfo
Y = data[['FRAUD']]

In [30]:
X.head()

TOTAL_SPEND  DOCTOR_VISITS  NUM_CLAIMS  MEMBER_DURATION  OPTOM_PRESC  \
0     0.000000       0.268293    0.000000         0.142424     0.058824   
1     0.002252       0.170732    0.133333         0.184848     0.000000   
2     0.004505       0.097561    0.000000         0.225758     0.058824   
3     0.004505       0.219512    0.000000         0.272727     0.058824   
4     0.006757       0.073171    0.000000         0.140909     0.000000   

   NUM_MEMBERS  
0     0.142857  
1     0.000000  
2     0.285714  
3     0.000000  
4     0.000000

In [31]:
Y.head()

FRAUD
0      1
1      1
2      1
3      1
4      0

#### Use the first 20% of the dataset i.e., the first 20% of the rows as the test set, while the remaining bottom 80% rows will be your training set.

In [32]:
print(list(data.shape))

splitNum = math.ceil(0.2 * list(data.shape)[0])

X_train = scaledInfo.iloc[splitNum:, :] # Use it for train purpose
X_test = scaledInfo.iloc[:splitNum, :] # Use it for test purpose

Y_train = Y.iloc[splitNum:, :]
Y_test = Y.iloc[:splitNum, :] 

[5960, 8]


In [33]:
X_test

TOTAL_SPEND  DOCTOR_VISITS  NUM_CLAIMS  MEMBER_DURATION  OPTOM_PRESC  \
0        0.000000       0.268293    0.000000         0.142424     0.058824   
1        0.002252       0.170732    0.133333         0.184848     0.000000   
2        0.004505       0.097561    0.000000         0.225758     0.058824   
3        0.004505       0.219512    0.000000         0.272727     0.058824   
4        0.006757       0.073171    0.000000         0.140909     0.000000   
...           ...            ...         ...              ...          ...   
1187     0.100225       0.731707    0.000000         0.493939     0.058824   
1188     0.100225       0.097561    0.000000         0.418182     0.000000   
1189     0.100225       0.048780    0.000000         0.039394     0.176471   
1190     0.100225       0.609756    0.666667         0.310606     0.176471   
1191     0.100225       0.219512    0.066667         0.230303     0.117647   

      NUM_MEMBERS  
0        0.142857  
1        0.000000  
2        0.285714  
3        0.000000  
4        0.000000  
...           ...  
1187     0.285714  
1188     0.285714  
1189     0.142857  
1190     0.000000  
1191     0.142857  

[1192 rows x 6 columns]

#### 2) You will use sklearn’s k – nearest neighbors module to learn a classification model with multiple nearest neighbors ranging from 2 to 5. Apply the learned k–NN model to classify the test set. Compute the misclassification rates for k ranging from 2 to 5. Use Euclidean distance as the similarity measure. (5 marks)

In [34]:
for i in range(2, 6):
    knn = KNeighborsClassifier(n_neighbors=i, metric='euclidean')
    knn.fit(X_train.squeeze(), Y_train.squeeze())
    y_pred = knn.predict(X_test)
    print("------------------------------------------------------------------------------------------------------------------------------------")
    print("The n-neighbour is :", i)
    print(y_pred,  len(y_pred))
    misclassification = 1 - accuracy_score(Y_test, y_pred)
    print(f"The misclassification when k = {i}, is {misclassification:.4f}")
    print("------------------------------------------------------------------------------------------------------------------------------------\n")

------------------------------------------------------------------------------------------------------------------------------------
The n-neighbour is : 2
[0 0 0 ... 0 1 0] 1192
The misclassification when k = 2, is 0.2777
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
The n-neighbour is : 3
[0 0 0 ... 0 1 1] 1192
The misclassification when k = 3, is 0.2894
------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------
The n-neighbour is : 4
[0 0 0 ... 0 1 0] 1192
The misclassification when k = 4, is 0.2844
---------------------------------------------------------------

#### 3) Next, apply sklearn’s k–d tree module to classify the test set. In a similar manner to the above scenario, compute the misclassification rates for k ranging from 2 to 5. Use Manhattan distance as the similarity measure. (5 marks)

In [35]:
for i in range(2, 6):
    print("-----------------------------------------------------------------------------------------------------------------------------------")
    knn = KNeighborsClassifier(n_neighbors=i, algorithm='kd_tree', metric='manhattan')
    knn.fit(X_train.squeeze(), Y_train.squeeze())
    y_pred = knn.predict(X_test)
    print("n_neighbors :",i)
    accuracyScore = 1 - accuracy_score(Y_test, y_pred)
    print(f"The n_neighbors are : {i} and its misclassification is : {accuracyScore:.4f}")
    print("-----------------------------------------------------------------------------------------------------------------------------------\n")


-----------------------------------------------------------------------------------------------------------------------------------
n_neighbors : 2
The n_neighbors are : 2 and its misclassification is : 0.2861
-----------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------
n_neighbors : 3
The n_neighbors are : 3 and its misclassification is : 0.2894
-----------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------
n_neighbors : 4
The n_neighbors are : 4 and its misclassification is : 0.2878
--------------------------------------------------------------------------------------------------------